events {}

http {
    server {
        listen 80;

        # Gelen tüm istekleri arka plandaki Go uygulamamıza yönlendir
        location / {
            proxy_pass http://go-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}